### ISSUE TITLE
Concurrent queries limit

### ISSUE THREAD

**Issue by electrical** [metrico/promcasa#3]
Hi,

we are trying Promcasa against Clickhouse with quite a large list of queries.
We are currently hitting this error:

```
{"level":"error","msg":"Error in future process:code: 202, message: Too many simultaneous queries. Maximum: 100","time":"2023-03-06T11:52:20Z"}
```

There seems to be nothing in place to limit the number of concurrent queries in promcasa?

**Comment by adubovikov** [comment]
You can increase the value in  /etc/clickhouse-server/config.xml

```
<max_concurrent_queries>200</max_concurrent_queries>
```

**Comment by electrical** [comment]
that's one way yeah, but also opens up the system for abuse.
I guess it's a feature request to allow limiting the concurrent queries done by promcasa.

**Comment by adubovikov** [comment]
I understand your point, you can play with this param - limit maxOpenConnection

https://github.com/metrico/promcasa/blob/main/config/config.go#L28

it'll create a waiting queue to send requests.
