### ISSUE TITLE
No configuration file loaded - checking env:  While parsing config: invalid character '\x7f' looking for beginning of value ERRO[0000] No configuration file loaded - using defaults - checking env    We don't have any active DB session configured. Please check your config

### ISSUE THREAD

**Issue by aitudorm** [metrico/promcasa#5]
Dear Promcasa devs, 
I encountered a problem while executing binary file of promcasa after configuring `/etc/promcasa.json` file.
Could you expand your tutorial with configuring `promcasa.json` file with another example of database and table. 
For example I have a table `orders` that has a column `date`. I want to see the count of table for the last hour and its' configuration in `/etc/promcasa,json`

Also it will be good if you add another information about how to configure /endpoint of clickhouse so it can show metrics with curl. Because I am struggling with it, when I run `curl 'localhost:8123/metrics'` it is shows me 0 result.

Thank you!

**Comment by lmangani** [comment]
Hello @aitudorm 

The configuration is simply a parameter of the binary. For instance `./promcasa config.json`
As of the ClickHouse queries, please refer to the examples and go from there. Note you need tags as well:

```
{
   "_info": "Custom Metrics from Clickhouse",
   "name": "my_status", // must be unique
   "help": "My Status",
   "query": "SELECT tags, count(*) as counter FROM orders FINAL PREWHERE (date>= toDateTime(now()-3600)) AND (date< toDateTime(now()) ) group by tags",
   "labels": ["tags"], // must match columns
   "counter_name": "counter",
   "refresh": "1h", //  Refesh takes unit sign: (ns, ms, s, m, h)
   "type":"gauge" // gauge, histogram, counter
}
```

Promcasa queries ClickHouse and exposes it's own `/metrics` endpoint.
Configuring an endpoint in ClickHouse is not part of the capabilities.

**Comment by aitudorm** [comment]
Ok then, is it required to install certain version of Golang  (1.19) on instance?

**Comment by lmangani** [comment]
@aitudorm not unless you want to compile it. just download a [release](https://github.com/metrico/promcasa/releases)

**Comment by aitudorm** [comment]
@lmangani could you explain how to configure connection to database? What does mean "table_prefix" in json configuration. How to specify to which database connect. Also is there any opportunity to add one more query to fetch another custom metric? Or I should deploy second prompaca config?

**Comment by lmangani** [comment]
It seems you have not actually tried to use promcasa. Please do and feel free to submit any actual issues you might find.
