### ISSUE TITLE
Is it possible to run one promcasa exporter in one instance but with two clickhouse service?

### ISSUE THREAD

**Issue by aitudorm** [metrico/promcasa#6]
Hello dev team!
I am currently working with cluster of clickhouse servers. I have in 1 - instance, 2 - services of Clickhouse. Is it possible to collect metrics from both of them via promcasa? I just thought about changing a config file like as below:
```
{
  "database_data": [
    {
      "help": "Settings for Clickhouse Database (data)",
      "user": "promcasa",
      "pass": "12345",
      "name": "db",
      "proto": "http",
      "host": "10.10.10.10",
      "port": 8123,
      "primary": true,
      "debug": true
    }
  ]
```
and add the same block but with port 8124
```
{
  "database_data": [
    {
      "help": "Settings for Clickhouse Database (data)",
      "user": "promcasa",
      "pass": "12345",
      "name": "db",
      "proto": "http",
      "host": "10.10.10.10",
      "port": 8124,
      "primary": true,
      "debug": true
    }
  ]
```
Will it work? If no, could you add this type of feature in futher time and would you mind to give me advice how to deal with my problem?

**Comment by aitudorm** [comment]
@lmangani @adubovikov

**Comment by adubovikov** [comment]
should work - it has array of connection
https://github.com/metrico/promcasa/blob/main/main.go#L214
